# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#VAGRANTFILE_API_VERSION = "2"

#Vagrant.require_version ">= 1.4.3"
Vagrant.configure(2) do |config|
  version = "latest"
  source = "../data"
  config.vm.define "vanilla_ckan_2.3.3"
  config.vm.box = "bento/centos-6.7"
  config.vm.box_check_update = false
  config.vm.provider :virtualbox do |vb|
   vb.name = "vagrant_ckan_2.3.3"
   vb.memory = 2048
  end

  config.vm.hostname = "vanillackan"

  # the bcgov vagrant uses default, this will allow to run both installs without worrying about conflicts
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
  config.vm.network :forwarded_port, guest: 22, host: 2220, auto_correct: true

  config.vm.network :forwarded_port, guest: 5050, host: 5050, id: "ckan"
  config.vm.network :forwarded_port, guest: 8983, host: 8984, id: "solr"

  config.vm.provision "shell", path: "provision.sh", :args => version
  config.vm.synced_folder source, "/usr/local/install_data"
end
