# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#VAGRANTFILE_API_VERSION = "2"

#Vagrant.require_version ">= 1.4.3"
Vagrant.configure(2) do |config|
  version = "latest"
  source = "../data"
  config.vm.box = "bento/centos-6.7"
  config.vm.provider :virtualbox do |vb|
   vb.name = "vagrant_bcdc"
   vb.memory = 2048
  end
  config.vm.network :forwarded_port, guest: 5000, host: 5000
  config.vm.network :forwarded_port, guest: 8983, host: 8983

  config.vm.provision "shell", path: "provision.sh", :args => version
  config.vm.synced_folder source, "/usr/local/install_data"

end
