# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#VAGRANTFILE_API_VERSION = "2"

#Vagrant.require_version ">= 1.4.3"
Vagrant.configure(2) do |config|
  version = "latest"

  ckan_src = "../src"
  logs = "../logs"
  conf = "../conf"

  config.vm.define "vanilla_ckan_master"
  config.vm.box = "bento/centos-6.8"
  config.vm.box_check_update = false

  config.vm.provider :virtualbox do |vb|
   vb.name = "vagrant_ckan_master"
   vb.memory = 2048
  end

  config.vm.hostname = "vanilla.ckan.master"

  config.vm.network "private_network", ip: "10.1.0.3"
  # For NAT use
  #config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
  #config.vm.network :forwarded_port, guest: 5050, host: 5050, id: "ckan"
  #config.vm.network :forwarded_port, guest: 8983, host: 8984, id: "solr"
  #config.vm.network :forwarded_port, guest: 5432, host: 5433, id: "pg"

  config.vm.provision "shell", path: "provision.sh", :args => version
  config.vm.synced_folder ckan_src, "/home/vagrant/ckan/src", create: true, owner: "vagrant", group: "vagrant"
  config.vm.synced_folder conf, "/apps/ckan/conf", create: true, owner: "vagrant", group: "vagrant"
  config.vm.synced_folder logs, "/apps/logs", create: true, owner: "vagrant", group: "vagrant"
end
